---
- name: INSTALLING TOR
  hosts: all
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"

  - name: Install the latest version of Tor and torsocks [RedHat Based]
    dnf:
      name: ['tor', 'torsocks']
      state: latest
    register: tor_package
    when: ansible_os_family == 'RedHat'


  - name: Install the latest version of Tor and torsocks [Debian Based]
    apt:
      name: ['tor', 'torsocks']
      update_cache: true
      state: present
    register: tor_package
    when: ansible_os_family == 'Debian'


  - name: Enable Systemd services
    systemd:
      name: tor
      enabled: yes
      daemon_reload: yes


  - name: Restart Tor
    systemd:
      name: tor
      state: restarted
    when: tor_package.changed
